import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MessagesLayout({
  children,messages,sidebar
}: {
  children: React.ReactNode,
  messages:React.ReactNode,
    sidebar:React.ReactNode
}) {
  return (
    <div
      className={`${inter.className} bg-[#1f2329] w-full h-full flex flex-row`}
    >
        {children}
        {sidebar}
      {messages}
    </div>
  );
}
